--truncate table mytime_china_amzn_attendance;
set wlm_query_slot_count to 5;
insert into mytime_china_amzn_attendance
select
  personid,
  personnum,
  employment_status,
  user_name,
  legal_name,
  employee_name,
  date_joined,
  termination_date,
  department,
  payrule,
  supervisor_legal_name,
  supervisor_name,
  employee_type,
  day_off_weekend,
  prolonged_sick_leave,
  paid_sick_leave,
  marriage_leave,
  absence,
  annual_leave,
  personal_leave,
  bereavement_leave,
  maternity_leave,
  unpaid_maternity_leave,
  paternity_leave,
  vto,
  other_paid_leave,
  other_unpaid_leave,
  prenatal_examination_leave,
  abortion_miscarriage_leave,
  prepartum,
  nursing_period,
  non_hol_actual_work_hours,
  holiday_actual_working_hour,
  night_shift_1,
  night_shift_2,
  etl_insert_timestamp,
  loc_cd,
  prolonged_personal_leave,
  parental_leave,
  injured_leaves_w_salary_paid,
  ot_public_holiday,
  actual_work_hours,
  transaction_date
from vw_mytime_china_amzn_attendance;

--COMMIT;
