--truncate table mytime_china_amzl_actual_working_days;
set wlm_query_slot_count to 5;
insert into mytime_china_amzl_actual_working_days
select
  personid,
  personnum,
  employmentstatus,
  username,
  chinesename,
  englishname,
  hiredate,
  terminationdate,
  costcenter,
  payrule,
  repdate,
  scheduled_rest_day,
  paid_sick_leave,
  annual_leave,
  personal_leave,
  absence,
  marriage_leave,
  bereavement_leave,
  other_paid_leave,
  other_unpaid_leave,
  paternity_leave,
  maternity_leave,
  unpaid_maternity_leave,
  prenatal_examination_leave,
  abortion_miscarriage_leave,
  prolonged_sick_leave,
  injured_leaves_w_salary_paid,
  pre_partum,  
  parental_leave,
  rest_on_public_holiday,
  acting_assistant_hours,
  acting_assistant_holiday_hours,
  attendance_without_package,
  ot_on_switch_weekend,
  ot_on_public_holiday,
  daily_interns_worked_days,
  night_shift_hours,
  night_shift_holiday_hours,
  etl_insert_timestamp,
  locationcode,
  nursing_period,
  prolong_personal_leave
from vw_mytime_china_amzl_actual_working_days

--commit;
