create external table xml_test
(
    ID string,
    NAME string,
    XML_BODY string
)
STORED AS AVRO
LOCATION 's3://mdmytro-dw3/staging/xml_test'
TBLPROPERTIES(
'avro.schema.literal'='
    {
    "type" : "record",
    "name" : "AutoGeneratedSchema",
    "doc" : "Sqoop import of QueryResult",
    "fields" : [ {
        "name" : "ID",
        "type" : [ "null", "string" ],
        "default" : null,
        "columnName" : "ID",
        "sqlType" : "2"
    }, {
        "name" : "NAME",
        "type" : [ "null", "string" ],
        "default" : null,
        "columnName" : "NAME",
        "sqlType" : "12"
    }, {
        "name" : "XML_BODY",
        "type" : [ "null", "string" ],
        "default" : null,
        "columnName" : "XML_BODY",
        "sqlType" : "12"
    } ],
    "tableName" : "QueryResult"
    }
'
)
